### ISSUE TITLE
小建议， pin的操作基于 rtt pin设备是不是更好 更通用

### ISSUE THREAD

**Issue by sogwms** [Sunwancn/rtt-pkgs-easyblink#1]

**Comment by Sunwancn** [comment]
基于rtt pin的设备代码看起来是简洁了，但不能同时适用Nano，到Nano版又要修改适配了。这个看起来代码量大，实际编译后代码不大，大部分是宏开关。效率应该说要比封装了一层的pin设备要高点。

**Comment by sogwms** [comment]
pin设备虽“臃肿”但统一了底层， 现在这个局限于 stm32 了，

**Comment by sogwms** [comment]
一点想法， 不用pin设备，通用的话。再抽象点，另搞个pin的抽象层好像更好？

**Comment by Sunwancn** [comment]
谢谢你的提议!是我局限了，当时想的是兼容Nano，再加上自己一直用的stm32，想当然了。非常感谢，想想得怎么改。发自手机-------- 原始邮件 --------主题：Re: [Sunwancn/rtt-pkgs-easyblink] 小建议， pin的操作基于 rtt pin设备是不是更好 更通用 (#1)发件人：Tevano 收件人：Sunwancn/rtt-pkgs-easyblink 抄送：Sunwancn ,Comment 

pin设备虽“臃肿”但统一了底层， 现在这个局限于 stm32 了，



—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/Sunwancn/rtt-pkgs-easyblink/issues/1#issuecomment-605979884",

"url": "https://github.com/Sunwancn/rtt-pkgs-easyblink/issues/1#issuecomment-605979884",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by Sunwancn** [comment]
不好统一，已经分离为标准版和Nano版，标准版基于PIN组件，支持更多平台，Nano版只支持STM32。
